trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'install gitversion'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global GitVersion.Tool'

- task: DotNetCoreCLI@2
  displayName: 'dotnet gitversion'
  inputs:
    command: 'custom'
    custom: 'gitversion'
    arguments: '/targetpath $(Build.SourcesDirectory) /output buildserver /updateassemblyinfo /updateprojectfiles'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/src/Functions.Extensions.Startup/Functions.Extensions.Startup.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/test/Functions.Extensions.Startup.Tests/Functions.Extensions.Startup.Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    packagesToPack: '**/src/Functions.Extensions.Startup/Functions.Extensions.Startup.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.NuGetVersion'